---
- name: install GHC
  apt: name=ghc state=present

- name: install Cabal
  apt: name=cabal-install state=present

- name: update Cabal
  become: yes
  become_user: "{{ user_name }}"
  command: cabal update
  args:
    creates: /home/{{ user_name }}/.cabal/packages/hackage.haskell.org/00-index.tar

- name: Install pandoc
  apt: name=pandoc state=present

- name: Install Pandoc optional dependencies
  apt: name=texlive state=present

- name: Install Criterion and System.Clock
  become: yes
  become_user: "{{ user_name }}"
  command: cabal install criterion clock
  args:
    creates: /home/{{ user_name }}/.cabal/packages/hackage.haskell.org/criterion/1.1.0.0/criterion-1.1.0.0.tar.gz

# - name: Install System.Clock
#   become: yes
#   become_user: {{ user_name }}
#   command: cabal install clock
#   args:
#     creates: "/home/{{ user_name }}/.cabal/packages/hackage.haskell.org/clock/0.7.1.1/clock-0.7.1.1.tar.gz"
