---

- name: Get LattE source archive
  become: yes
  become_user: jmct
  get_url: url=https://www.math.ucdavis.edu/~mkoeppe/latte/download/experimental/latte-integrale-1.7.3b.tar.gz dest=/home/jmct/latte-integrale-1.7.3b.tar.gz

- name: Unarchive LattE source
  become: yes
  become_user: jmct
  unarchive: src=/home/jmct/latte-integrale-1.7.3b.tar.gz dest=/home/jmct/ copy=no
  args:
    creates: /home/jmct/latte-integrale-1.7.3b/

- name: run configure for LattE
  become: yes
  become_user: jmct
  shell: ./configure
  args:
    chdir: /home/jmct/latte-integrale-1.7.3b
    creates: /home/jmct/latte-integrale-1.7.3b/Makefile

- name: make LattE
  become: yes
  become_user: jmct
  shell: make
  args:
    chdir: /home/jmct/latte-integrale-1.7.3b
    creates: /home/jmct/latte-integrale-1.7.3b/dest/bin/count

- name: Put LattE count in PATH
  become: yes
  shell: cp /home/jmct/latte-integrale-1.7.3b/dest/bin/count /usr/bin/
  args:
    creates: /usr/bin/count

- name: Put latte-maximize in PATH
  become: yes
  shell: cp /home/jmct/latte-integrale-1.7.3b/dest/bin/latte-maximize /usr/bin/
  args:
    creates: /usr/bin/latte-maximize

#- name: Install necessary LattE binaries
#  become: yes
#  shell: make install
#  args:
#    chdir: /usr/share/ppl-1.1
