---

- name: Get PPL source archive
  get_url: url=ftp://ftp.cs.unipr.it/pub/ppl/releases/1.1/ppl-1.1.tar.bz2 dest=/usr/share/ppl-1.1.tar.bz2

- name: Unarchive PPL source
  unarchive: src=/usr/share/ppl-1.1.tar.bz2 dest=/usr/share/ copy=no

- name: run configure for PPL lib
  become: yes
  become_user: jmct
  shell: ./configure --enable-interfaces=ocaml --with-mlgmp=/home/jmct/.opam/4.02.0/lib/gmp/ CFLAGS=-g
  args:
    chdir: /usr/share/ppl-1.1
    creates: /usr/share/ppl-1.1/Makefile

- name: make PPL
  become: yes
  become_user: jmct
  shell: bash -c 'eval `opam config env`; make'
  args:
    chdir: /usr/share/ppl-1.1
    creates: /usr/share/ppl-1.1/src/.libs/libppl.so

- name: Install PPL
  become: yes
  shell: make install
  args:
    chdir: /usr/share/ppl-1.1
    creates: /usr/local/lib/libppl.so

- name: Add /usr/local/lib to ld.so.conf
  become: yes
  shell: echo "/usr/local/lib" >> /etc/ld.so.conf && ldconfig && touch /root/.ppl-path
  args:
    creates: /root/.ppl-path
