---

- name: Create qif directory
  file: path=/vagrant/qif state=directory

- name: Get prob sources
  become: yes
  become_user: vagrant
  shell: git clone https://github.com/plum-umd/qif.git /vagrant/qif
  args:
    creates: /vagrant/qif/README.md

- name: Build prob
  shell: make prob
  args:
    chdir: /vagrant/qif/prob
    creates: /vagrant/qif/prob/prob
