---

- name: Build prob
  become: yes
  become_user: vagrant
  shell: eval `opam config env`; make prob
  args:
    chdir: /vagrant/code/prob
    creates: /vagrant/code/prob/prob

- name: Install prob
  become: yes
  shell: cp ./prob /usr/local/bin/prob
  args:
    chdir: /vagrant/code/prob
    creates: /usr/local/bin/prob
