---

- name: Build prob
  become: yes
  become_user: "{{ user_name }}"
  shell: eval `opam config env`; make prob
  args:
    chdir: "{{ build_dir }}"
    creates: "{{ build_dir }}/prob"

- name: Install prob
  become: yes
  shell: cp ./prob /usr/local/bin/prob
  args:
    chdir: "{{ build_dir }}"
    creates: /usr/local/bin/prob
