---
- name: install dkms
  apt: name=dkms state=present

- name: install C compiler
  apt: name=gcc state=present

- name: install C++ compiler
  apt: name=g++ state=present

- name: install vim
  apt: name=vim state=present

- name: install emacs
  apt: name=emacs state=present

- name: install wget
  apt: name=wget state=present

- name: install git
  apt: name=git state=present

- name: install libcdd
  apt: name=libcdd-test state=present

- name: link scdd_gmp in /usr/bin/
  shell: ln -s /usr/lib/cdd-test/scdd_gmp /usr/bin/scdd_gmp
  args:
    creates: /usr/bin/scdd_gmp
