---
title: "Support Estimation Under Region Composition"
author: "Chad Scherrer"
date: "April 22, 2016"
output: html_document
---

##Support size estimation

Suppose we have two regions, $R_1$ and $R_2$, with $R_j$ containing $n_j$ points. For each region, we sample from the $n_j$ points and determine whether a given selected point is in the support of some query. From some sample, let $\alpha_j$ and $\beta_j$ be the number of sampled points inside and outside the support, respectively. 

For each region, there is some unknown number $s_j$ of points in the support. We can use $\alpha_j$ and $\beta_j$ to arrive at a credible interval for $s_j$, since the probability of success (*i.e.*, of satisfying the query) can be assumed to follow a $\text{Beta}(\alpha_j,\beta_j)$ distribution.

##Composition

So far, so good. But now we'd like to use what we know so far to arrive at a credible interval for $s=s_1+s_2$. This is given by a linear combination of beta distributions (as random variables, not pointwise, so a convolution is required). Unfortunately, such a linear combination is not, in general, another beta distribution. Naively, we'd be stuck with a "mixture of betas", with the same number of components as there are regions. Computing quantiles in order to find a credible interval would be a mess.

But there's something that could help. As $\alpha + \beta \rightarrow \infty$, the $\text{Beta}(\alpha_j,\beta_j)$ distribution asymptotically approaches a normal distribution. Scaling this by the region size $n$ yields mean and variance parameters

$$
\mu = \frac{n \alpha}{\alpha+\beta} \\
\sigma^2 = \frac{n^2 \alpha \beta}{(\alpha + \beta)^2 (\alpha + \beta + 1)}\ .
$$

The class of normal distributions is *stable*, which in particular means the class is closed under linear combinations. In the case we're looking at, it's especially simple: **To add two disjoint regions, just add the means, and add the variances.**

##A possible approach

Ok, so here's a straw-man. We already have a nice type separation of "region" vs "join of regions". We can build on this and allow different distributional information to be stored on each.

For a single region, we can include the number of true and false results for the query, as we're already doing. The only difference will be that in order to accomodate upcoming steps, we need to be sure that enough samples have been taken for the normal approximation to be reasonably good. 

For a join of some set of regions, the beta distribution parameters for each leaf region are mapped to the corresponding normal distribution. Instead of the beta parameters, these normal distribution parameters are included in the type.

##Risks

As described above, composition is very simple; means and variances just add. However, there are still some difficulties.

First, new samples cannot be introduced directly. The easiest way I can see around this is to include an option to convert back to a beta, add some samples, and then convert again to a normal. But each such conversion is an approximation, and it's not immediately clear how lossy it is.

There's also the issue of the quality of the approximation, and how many samples is enough. For $\alpha \approx \beta$, the approximation converges very quickly. But if either is near zero, it can take a large number of samples. 